name: Build Linux x86_64

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Check format
        run: zig fmt --check build.zig build.zig.zon evilblog.zon src/*.zig
      - name: Test
        run: zig build test -Dversion=0.0.0-ci
      - name: Build
        run: zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux-musl -Dversion=0.0.0-ci
