name: Build Linux aarch64

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build
        run: zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-linux-musl -Dversion=0.0.0-ci
